name: Build and deploy Python app to Azure Web App - communityapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and run gunicorn
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          cd Backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          gunicorn server:app
